<a href="https://colab.research.google.com/github/NAVEEN8103/PracticeDataScience/blob/main/Numpy_practice_by_DataMites.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[12,13,14],
              [22,23,24],
              [32,33,34]])
b = np.array([[42,43,44],
              [52,53,54],
              [62,63,64]])

In [ ]:
print(a)
print(b)

[[12 13 14]
 [22 23 24]
 [32 33 34]]
[[42 43 44]
 [52 53 54]
 [62 63 64]]


In [ ]:
a*b

array([[ 504,  559,  616],
       [1144, 1219, 1296],
       [1984, 2079, 2176]])

In [ ]:
np.dot(a,b)

array([[2048, 2087, 2126],
       [3608, 3677, 3746],
       [5168, 5267, 5366]])

In [ ]:
a.dot(b)

array([[2048, 2087, 2126],
       [3608, 3677, 3746],
       [5168, 5267, 5366]])

In [ ]:
#


In [ ]:
my_arr = np.array(["I","Love","Banglore","very","much."])
my_arr

array(['I', 'Love', 'Banglore', 'very', 'much.'], dtype='<U8')

In [ ]:
type(my_arr)
my_arr.shape

(5,)

In [ ]:
upper_my_arr = np.char.upper(my_arr)
upper_my_arr

array(['I', 'LOVE', 'BANGLORE', 'VERY', 'MUCH.'], dtype='<U8')

In [ ]:
lower_my_arr = np.char.lower(my_arr)
lower_my_arr

array(['i', 'love', 'banglore', 'very', 'much.'], dtype='<U8')

In [ ]:
caps_my_arr = np.char.capitalize(my_arr)
caps_my_arr

array(['I', 'Love', 'Banglore', 'Very', 'Much.'], dtype='<U8')

In [ ]:
title_my_arr = np.char.title(my_arr)
title_my_arr

array(['I', 'Love', 'Banglore', 'Very', 'Much.'], dtype='<U8')

In [ ]:
swapcase_my_arr = np.char.swapcase(my_arr)
swapcase_my_arr

array(['i', 'lOVE', 'bANGLORE', 'VERY', 'MUCH.'], dtype='<U8')

In [ ]:
# GET ROW NUMBERS OF NUMPY ARRAY IF ANY ELEMENT IS HAVING LARGER VALUE THEN SPECIFIED VALUE

In [ ]:
my_arr = np.array([[1,2,3,4,5],
                  [0,-42,-3,10,2],
                  [32,42,12,1,1],
                  [90,34,5,6,7],
                  [324,535,6,7,9],
                  [1,2,3,443,5]])

In [ ]:
np.any(my_arr >40,axis =1)

array([False, False,  True,  True,  True,  True])

In [ ]:
np.where(np.any(my_arr >40,axis =1))

(array([2, 3, 4, 5]),)

In [ ]:
# HOW TO REMOVE ROWS WHICH CONTAINS NULL VALUES IN NUMPY ARRAY

In [ ]:
my_arr =np.array([[12,24,45,6,46],
                  [23,23.2,2423.1,324.3,22.12],
                  [34,np.nan,342,32,54],
                  [6,7,4,np.nan,1]])
my_arr

array([[1.2000e+01, 2.4000e+01, 4.5000e+01, 6.0000e+00, 4.6000e+01],
       [2.3000e+01, 2.3200e+01, 2.4231e+03, 3.2430e+02, 2.2120e+01],
       [3.4000e+01,        nan, 3.4200e+02, 3.2000e+01, 5.4000e+01],
       [6.0000e+00, 7.0000e+00, 4.0000e+00,        nan, 1.0000e+00]])

In [ ]:
my_arr[~np.isnan(my_arr).any(axis=1)]

array([[  12.  ,   24.  ,   45.  ,    6.  ,   46.  ],
       [  23.  ,   23.2 , 2423.1 ,  324.3 ,   22.12]])

In [ ]:
# HOW TO MULTIPLY A STRING ELEMENT WITH A NUMPY ARRAY

In [ ]:
3*"APPLE"

'APPLEAPPLEAPPLE'

In [ ]:
my_arr = np.array(["Naveen",'Aman','Shivani','Adesh','Kalawati'])
new_my_arr = np.char.multiply(my_arr,4)

In [ ]:
new_my_arr

array(['NaveenNaveenNaveenNaveen', 'AmanAmanAmanAman',
       'ShivaniShivaniShivaniShivani', 'AdeshAdeshAdeshAdesh',
       'KalawatiKalawatiKalawatiKalawati'], dtype='<U32')

In [ ]:
# HOW TO SELECT THE MINIMUM VALUES ALONG AXIS


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.apply_along_axis(lambda x: np.min(x), arr = a, axis = 1)

array([1, 4, 7])

In [ ]:
np.apply_along_axis(lambda x: np.min(x), arr = a, axis = 0)

array([1, 2, 3])

In [ ]:
# HOW DO YOU FILL A DIAGONAL VALUE WITH THE NUMBER OF A NUMPY ARRAY.

In [ ]:
my_arr =  np.array([[8,9],[6,7]])
my_arr

array([[8, 9],
       [6, 7]])

In [ ]:
x = 5

In [ ]:
# METHOD 1
def filldiag(my_arr, x):
  for i in range(len(my_arr)):
    for j in range(len(my_arr[0])):
      if i ==j :
        my_arr[i][j] = x
  return my_arr

In [ ]:
filldiag(my_arr,x)

array([[5, 9],
       [6, 5]])

In [ ]:
# METHOD 2
np.fill_diagonal(my_arr, x)

In [ ]:
my_arr

array([[5, 9],
       [6, 5]])

In [ ]:
# HOW TO CHECK IF A CERTAIN NUMBER IS PRESENT IN A NUMPY ARRAY AND FILL ALL THE NEGATIVE VALUES WITH 8.

In [ ]:
my_arr =  np.array([1,2,3,4,5,6,-2,34,53,-4,242,453,5,43,6,-3])
my_arr

array([  1,   2,   3,   4,   5,   6,  -2,  34,  53,  -4, 242, 453,   5,
        43,   6,  -3])

12 is present in numpy array or not

In [ ]:
np.isin(my_arr, 12)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
np.isin(my_arr, 3)

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
np.isin(my_arr,[2,3,5,6,7,78,8,9])

array([False,  True,  True, False,  True,  True, False, False, False,
       False, False, False,  True, False,  True, False])

In [ ]:
my_arr[my_arr <0] = 8

In [ ]:
my_arr

array([  1,   2,   3,   4,   5,   6,   8,  34,  53,   8, 242, 453,   5,
        43,   6,   8])

In [ ]:
# WRITE A NUMPY PROGRAM TO CREATE 4X4 ARRAY WITH RANDOM VALUES , NOW CREATE A NEW ARRAY FROM THE SAID ARRAY SUCH THAT IT STARTS WITH THE LAST ROW AND GOES TILL THE FIRST.

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
new_arr = my_arr[::-1]

In [ ]:
new_arr

array([  8,   6,  43,   5, 453, 242,   8,  53,  34,   8,   6,   5,   4,
         3,   2,   1])

In [ ]:
# HOW WILL YOU BORDER AROUND 2D NUMPY ARRAY.  (PADDING)

In [ ]:
my_arr =  np.ones((2,3))

In [ ]:
my_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.pad(my_arr,pad_width=1,mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# CALCULATE THE SIN AND COS VALUES OF THE NUMBERS GIVEN IN A NUMPY ARRAY.

In [ ]:
my_arr = np.array([0,30,45,60,90])
my_arr

array([ 0, 30, 45, 60, 90])

In [ ]:
np.sin(my_arr)
# -------------------->> this is not giving the correct value because here the sin of numpy accepts the value in radian form.

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [ ]:
new_arr = my_arr * np.pi/180

In [ ]:
new_arr

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [ ]:
np.sin(new_arr)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [ ]:
np.cos(new_arr)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [ ]:
# REMOVE SINGLE DIMENSION ENTERIES AND CHECK WETHER A SPECIFIED VALUE IS PRESENT IN NUMPY  ARRAY OR NOT.

In [ ]:
my_arr = np.array([[[2,3,4],[6,7,8]]])
my_arr

array([[[2, 3, 4],
        [6, 7, 8]]])

In [ ]:
my_arr.shape

(1, 2, 3)

In [ ]:
new_arr =  np.squeeze(my_arr)
new_arr

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
new_arr.shape

(2, 3)

In [ ]:
print(3 in new_arr)
print(4 in new_arr)

True
True


In [ ]:
print(5 in new_arr)

False


In [71]:
# COMPARE TWO NUMPY ARRAY

In [72]:
a= np.array([121,23,43])
b = np.array([34,54,65])

In [73]:
a>b

array([ True, False, False])

In [74]:
np.greater(a,b)

array([ True, False, False])

In [75]:
a>= b

array([ True, False, False])

In [76]:
np.greater_equal(a,b)

array([ True, False, False])

In [77]:
np.less_equal(a,b)

array([False,  True,  True])

In [78]:
a<b

array([False,  True,  True])

In [79]:
# HOW TO STACK TWO ARRAYS


In [81]:
a = np.arange(10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)

In [83]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [84]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [85]:
np.concatenate([a,b],axis = 1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [86]:
np.concatenate([a,b],axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
np.c_[a,b]

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [91]:
np.r_[a,b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
# HOW TO PUT VALUES FROM A NUMPY ARRAY OVER ANOTHER NUMPY ARRAY AT CERTAIN POSITION.

In [93]:
arr1 = np.array([12,3,34,4,46,65656,56,5,6565,54])
arr2 = np.array([23,4,64])

In [94]:
arr1.put([2,4,7],arr2)

In [95]:
arr1

array([   12,     3,    23,     4,   345, 65656,    56,   545,  6565,
          54])

In [96]:
# DELETE THE SECOND COLUMN FROM A GIVEN ARRAY AND INSERT THE FOLLOWING NEW COLUMN IN ITS PLACE.

In [98]:
array1 = np.arange(9).reshape((3,3))

In [99]:
column = np.array([23,34,45])

In [100]:
array1 = np.delete(array1,1,axis=1)

In [101]:
print(array1)

[[0 2]
 [3 5]
 [6 8]]


In [103]:
np.insert(array1,1,column,axis = 1)

array([[ 0, 23,  2],
       [ 3, 34,  5],
       [ 6, 45,  8]])

In [104]:
# WRITE A NUMPY PROGRAM TO CREATE AN ARRAY OF 10 ZEROS , 10 ONES, 10 FIVES.

In [106]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
c = np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [111]:
# HOW TO CREATE A RANDOM SEQUENCES IN NUMPY WITHOUT HARDCODING.

In [116]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [117]:
b= np.repeat(a,4)

In [118]:
c = np.tile(a,4)

In [119]:
np.concatenate([b,c])

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3])

In [120]:
# WRITE A NUMPY PROGRAM TO CREATE AN ARRAY WITH THE VALUES 1,7,13,105 AND DETERMINE THE SIZE OF THE MEMORY OCCUPIED BY THE ARRAY.

In [122]:
array1 = np.array([1,7,13,105])

In [123]:
array1.itemsize

8

In [124]:
array1.itemsize * len(array1)

32

In [126]:
array1.size * array1.itemsize

32